export const BOOKMARK_ADD_REQ = "BOOKMARK_ADD_REQ";
export const BOOKMARK_ADD_SUCCESS = "BOOKMARK_ADD_SUCCESS";
export const BOOKMARK_ADD_FAIL = "BOOKMARK_ADD_FAIL";
export const BOOKMARK_ADD_RESET = "BOOKMARK_ADD_RESET";
 
export const BOOKMARK_REMOVE_REQ = "BOOKMARK_REMOVE_REQ";
export const BOOKMARK_REMOVE_SUCCESS = "BOOKMARK_REMOVE_SUCCESS";
export const BOOKMARK_REMOVE_FAIL = "BOOKMARK_REMOVE_FAIL";
export const BOOKMARK_REMOVE_RESET = "BOOKMARK_REMOVE_RESET";

export const BOOKMARK_GET_REQ = "BOOKMARK_GET_REQ";
export const BOOKMARK_GET_SUCCESS = "BOOKMARK_GET_SUCCESS";
export const BOOKMARK_GET_FAIL = "BOOKMARK_GET_FAIL";
export const BOOKMARK_GET_RESET = "BOOKMARK_GET_RESET";