export const GET_NASA_EPIC_REQ = "GET_NASA_EPIC_REQ";
export const GET_NASA_EPIC_SUCCESS = "GET_NASA_EPIC_SUCCESS";
export const GET_NASA_EPIC_FAIL = "GET_NASA_EPIC_FAIL";
export const NASA_EPIC_RESET = "NASA_EPIC_RESET";

export const GET_NASA_APOD_REQ = "GET_NASA_APOD_REQ";
export const GET_NASA_APOD_SUCCESS = "GET_NASA_APOD_SUCCESS";
export const GET_NASA_APOD_FAIL = "GET_NASA_APOD_FAIL";
export const NASA_APOD_RESET = "NASA_APOD_RESET";

export const GET_NASA_ROVERS_REQ = "GET_NASA_ROVERS_REQ";
export const GET_NASA_ROVERS_SUCCESS = "GET_NASA_ROVERS_SUCCESS";
export const GET_NASA_ROVERS_FAIL = "GET_NASA_ROVERS_FAIL";
export const NASA_ROVERS_RESET = "NASA_ROVERS_RESET";