export const USER_REGISTRATION_REQ = "USER_REGISTRATION_REQ";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";
export const USER_REGISTRATION_RESET = "USER_REGISTRATION_RESET";

export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_REQ = "USER_UPDATE_REQ";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_REMOVE_REQ = "USER_REMOVE_REQ";
export const USER_REMOVE_SUCCESS = "USER_REMOVE_SUCCESS";
export const USER_REMOVE_FAIL = "USER_REMOVE_FAIL";
export const USER_REMOVE_RESET = "USER_REMOVE_RESET";